BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: user_input
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
        on_press: app.convert_miles_to_kilometres(user_input.text)
    Label:
        id: output_text
        color: (1, 1, 1, 1)